language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer require satooshi/php-coveralls:1.*

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

script: phpunit tests/ChronosTest.php